### PR TITLE
Improvement: Switch from `/srv/crate` to `/var/lib/crate` for external volumes

### PR DESCRIPTION
**Pull request by mechanomi**
(closes https://github.com/crate/crate-howtos/issues/211)

Also included: general copyedit for this subsection.

### CODE REVIEW

**Review by justien — COMMENTED** [review]
lgtm!

**Review by amotl — CHANGES_REQUESTED** [review]
Hi Naomi,

I would not recommend `/mnt` for production use. `/mnt` is meant to be a temporary mount point used by system administrators, see also [1,3]. Also, `/media` would not fit as it designates a mount point used for removable devices [2,3]. I also wonder why `/srv` was chosen here beforehand.

I would strongly suggest to follow the principle of least surprise and recommend to use `/var/lib/cratedb` as other database systems are doing so. For example, `/var/lib/mysql`, `/var/lib/mongodb`, `/var/lib/influxdb` and so forth. This is also clearly reflected within the FHS [4]:

> Directory | Description
> -- | --
> /srv | Site-specific data served by this system, such as data and scripts for web servers, data offered by FTP servers, and repositories for version control systems (appeared in FHS-2.3 in 2004).
> /var/lib | State information. Persistent data modified by programs as they run, e.g., databases, packaging system metadata, etc.

<br/>

With kind regards,
Andreas.


[1] https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/mnt.html
[2] https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/media.html
[3] https://unix.stackexchange.com/questions/13975/mounting-a-device-role-of-dev-media-and-mnt-and-the-mount-command
[4] https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure

**Comment by mechanomi** [comment]
@amotl omg thanks! very clear. makes sense. pushed a fixup

**Comment by amotl** [comment]
Thanks for fixing this. In order to discriminate between Rust's Cargo package management system [1], which is using the term "Crate" for its artifacts, I would really like to see `/var/lib/cratedb` being used here. However, our distribution packages already nailed it to use `/var/lib/crate` [2], so we should probably keep it like that.

[1] https://doc.rust-lang.org/cargo/
[2] https://github.com/crate/distribute

**Review by amotl — APPROVED** [review]

**Pull request merged**
